title: Laaija Oinam
description: Dreamer, artist, animator

remote_theme: oinam/oinam-jekyll

footer:
  custom: true

footer_custom: "© 2008 - <script>document.write(new Date().getFullYear())</script>. All Rights Reserved. Laaija."

styles:
  forms: false
  syntax_highlighter: false